<div id="page-header">
  <ul class="links" id="page-menu">
    <li>
      <a href="/">Home</a>
    </li>
    <li>
      <a href="/packages/">Browse</a>
    </li>
    <li>
      <a href="/accounts">User accounts</a>
    </li>
    <li>
      <form action="/packages/search" class="search" method="get">
        <button type="submit">Search</button>
        <input type="text" name="terms">
      </form>
    </li>
  </ul>
  <p class="caption"> Hackage :: $docTitle$</p>
</div> <!-- /page-header -->
